DATA:
  - name: "data_ingestion"
    type: "ingestion"
    bucket: "mlflow"
    source: "house.csv"
    destination: "data/raw"
    parameters:
      format: "csv"
      delimiter: ","
      header: true
  